// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zpfouxphwgtqhgalzyqk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpwZm91eHBod2d0cWhnYWx6eXFrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1OTc5MTYsImV4cCI6MjA2NTE3MzkxNn0.uzlPeumvFwJKdGR5rHyclBkc5ZMFH5NhJ41iROfRZmU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);