name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint

  build:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker image
        run: docker build -t sage-liquid-glow-design:latest .
      - name: Test Docker image
        run: |
          docker run -d -p 8080:80 --name test-container sage-liquid-glow-design:latest
          sleep 5
          curl -s --retry 10 --retry-connrefused http://localhost:8080 > /dev/null
          docker stop test-container

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to Render
        run: curl -s "${{ secrets.RENDER_DEPLOY_HOOK }}" 